void LED_Init(void);
void LED_Red(void);
void LED_Green(void);
void OS_FS_Init(void);
uint8_t OS_File_New( void);
uint8_t OS_File_Size(uint8_t);
uint8_t find_free_sector(void);
uint8_t last_sector(uint8_t);
void append_fat(uint8_t, uint8_t);
uint8_t OS_File_Read( uint8_t, uint8_t, uint8_t*);
uint8_t eDisk_WriteSector(uint8_t*, uint8_t);
uint8_t OS_File_Flush( void);
int Flash_Erase(uint32_t);
uint8_t OS_File_Format( void);
uint8_t OS_File_Append(uint8_t num, uint8_t buf[512]);
